<?php

declare(strict_types=1);

namespace Refilament\Refilament\Resources\Pages;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route as RouteFacade;
use Illuminate\Support\Str;
use LogicException;
use Refilament\Refilament\Actions\Action;
use Refilament\Refilament\Actions\CreateAction;
use Refilament\Refilament\Actions\DeleteAction;
use Refilament\Refilament\Clusters;
use Refilament\Refilament\Http\Controllers\ResourcePageController;
use Refilament\Refilament\Http\Middleware\AppendInertiaVersion;
use Refilament\Refilament\Http\Middleware\Authenticate as PanelAuthenticate;
use Refilament\Refilament\Pages\Page as BasePage;
use Refilament\Refilament\Refilament;
use Refilament\Refilament\Resources\Resource;
use Refilament\Refilament\Widgets\Widget;

/**
 * Resource page base (slice 1.6 — docs/ROADMAP.md "1.6 Page system").
 *
 * The base for every page a resource declares in its getPages() map. The
 * built-in list/create/edit/view pages extend this class; custom resource
 * pages do too, declaring their resource and adding their own extra props
 * via getViewData(). Payloads are built server-side per request — the page
 * knows its Inertia component and its props, and the package registers one
 * route per getPages() entry at boot.
 */
abstract class Page extends BasePage
{
    /**
     * The resource this page belongs to. Pages generated by
     * `refilament:make-resource` declare it explicitly; pages resolved from
     * the URL resource segment at request time (the built-ins used directly
     * in a hand-written getPages() map) leave it null and the controller
     * supplies the resource context (docs/ARCHITECTURE.md).
     *
     * @var class-string<resource>|null
     */
    protected static ?string $resource = null;

    /**
     * The crumb this page shows for itself in breadcrumbs (slice 1.11 —
     * docs/ROADMAP.md "1.11 Breadcrumbs"). Defaults to the page title
     * (mirroring Filament's `$breadcrumb ?? getTitle()`); the built-in
     * list/create/edit/view pages set "List" / "Create" / "Edit" / "View"
     * — exactly Filament's page breadcrumb defaults.
     */
    protected static ?string $breadcrumb = null;

    /**
     * The cluster this page belongs to (the page-clusters slice). A resource
     * page inherits its resource's cluster — declaring `$cluster` on the
     * resource groups every one of its pages under the cluster (sidebar
     * sub-navigation + the cluster breadcrumb crumb). Best-effort: only when
     * the page declares its `$resource` (built-ins used directly in a
     * hand-written getPages() map leave it null and the controller supplies
     * the context, so there is no cluster to inherit there).
     *
     * @return class-string<Clusters\Cluster>|null
     */
    public static function getCluster(): ?string
    {
        $cluster = parent::getCluster();

        if ($cluster !== null || static::$resource === null) {
            return $cluster;
        }

        return static::getResource()::getCluster();
    }

    /**
     * The resource class this page belongs to (custom pages declare it via
     * the $resource property).
     *
     * @return class-string<resource>
     */
    public static function getResource(): string
    {
        if (static::$resource === null) {
            throw new LogicException('Page ['.static::class.'] must declare a [$resource] property.');
        }

        return static::$resource;
    }

    /**
     * Register this page under a route path relative to the resource segment
     * ('/' for the list, '/create', '/{record}/edit', or a custom slug like
     * '/stats'). Mirrors Filament's Page::route(): the returned registration
     * is what Resource::getPages() returns, and the package registers the
     * route at boot — once per page name (all resources share the built-in
     * URI shapes, and the route collection keys by method|uri, so the first
     * resource to declare a page name wins its path). The route is
     * where()-gated to the ids discovered at boot (never an unconstrained
     * catch-all, so app-owned routes like /refilament/playground are not
     * shadowed) and its {record} segment is constrained to [0-9]+ so page
     * slugs never collide with record ids. The {record} constraint does mean
     * record pages assume integer primary keys today (docs/CONTRACT.md,
     * "Pages") — the where() gate itself is built from the ids discovered at
     * boot, which is non-empty exactly when this closure runs (the provider
     * only registers routes for discovered resources).
     */
    public static function route(string $path): PageRegistration
    {
        return new PageRegistration(
            page: static::class,
            path: $path,
            // The URI keeps the {resource} placeholder — the where() gate
            // constrains it to the ids discovered at boot, and the record
            // segment to integers, so the shared route shape is the same for
            // every resource and page slug. The route mounts under the
            // panel's URL prefix (a consumer's ->path('admin') moves it), and
            // carries the framework's `web` middleware group (sessions +
            // CSRF) plus the panel's middleware ahead of the access gate.
            route: static function (string $routeName) use ($path): Route {
                $refilament = app(Refilament::class);

                return RouteFacade::get(
                    $refilament->panel()->url('/{resource}'.$path),
                    [ResourcePageController::class, 'show'],
                )
                    ->where('resource', implode('|', array_map('preg_quote', $refilament->getResourceTableIds())))
                    ->where('record', '[0-9]+')
                    ->middleware(['web', ...$refilament->panel()->getMiddleware(), PanelAuthenticate::class, AppendInertiaVersion::class])
                    ->name($routeName);
            },
        );
    }

    /**
     * Build the Inertia props for this page. $resource is the URL segment
     * the page was served under (authoritative — custom pages may also
     * declare $resource for navigation); $record is the {record} route
     * param on record pages.
     *
     * @return array<string, mixed>
     */
    public static function getPayload(string $resource, Refilament $refilament, ?string $record = null): array
    {
        // The record model on record pages — threaded into the header-action
        // serializer so EditAction/ViewAction resolve their per-record page
        // URL and server actions (DeleteAction) serialize a runnable endpoint
        // (the record-scoped page-action slice). Resolved the same way the
        // breadcrumb serializer does; a stale record simply yields none.
        $recordModel = null;

        if ($record !== null) {
            $recordModel = static::getRecordRouteBindingEloquentQuery($resource)->find((string) $record);
        }

        // The page's slot name in the resource's getPages() map — needed by
        // the record-scoped form serializer to build its submit endpoint URL
        // (and by the header-action serializer for record-scoped actions).
        $pageName = static::pageSlotName($refilament, $resource);

        return [
            'resource' => $resource,
            'resourceTitle' => static::getResourceTitle($resource),
            // Page-level breadcrumbs (slice 1.11), header actions (slice 1.10)
            // and header/footer widgets ride on every resource page — the
            // list page's CreateAction and a stats strip above the table are
            // the canonical examples.
            ...static::serializeBreadcrumbs($resource, $refilament, $record),
            ...static::serializeHeaderActions($resource, $refilament, $recordModel),
            ...static::serializePageWidgets(),
            // A custom resource page hosting a form (the page-forms slice),
            // an infolist (the page-infolists slice) or a table (the
            // pages-as-tables slice) merges its payload here — a record
            // page's form/infolist binds the URL record, so a
            // `/{record}/manage` page reads and edits the record it manages
            // with zero consumer code beyond declaring the schema. The
            // built-in record pages declare none of these, so they
            // contribute nothing and their own pipelines stay untouched.
            ...static::serializePageForm($recordModel, $resource, $pageName),
            ...static::serializePageInfolist($recordModel),
            ...static::serializePageTable(),
            ...static::getViewData($resource),
        ];
    }

    /**
     * The crumb this page shows for itself in breadcrumbs (slice 1.11) — the
     * `$breadcrumb` override, else the page title. Mirrors Filament's
     * `Page::getBreadcrumb()`. The built-in list/create/edit/view pages set
     * "List" / "Create" / "Edit" / "View"; a custom page shows its own
     * title (e.g. "Post Stats").
     */
    public static function getBreadcrumb(): string
    {
        return static::$breadcrumb ?? static::getTitle();
    }

    /**
     * Whether this page's breadcrumbs start with the resource's crumb (slice
     * 1.11) — the list-page crumb the page links back to. Mirrors Filament's
     * `hasResourceBreadcrumbs()`, which defaults to true; override to drop the
     * resource crumb for pages that don't belong under the list (e.g. a
     * dashboard-like custom page).
     */
    public static function hasResourceBreadcrumbs(): bool
    {
        return true;
    }

    /**
     * The resource crumb for this page's breadcrumbs (slice 1.11) — the
     * resource's breadcrumb label, linking to its list page. Mirrors
     * Filament's `getResourceBreadcrumbs()` (without the parent-resource
     * chain, which our flat resources don't have).
     *
     * @return array<int, array{label: string, url: string}>
     */
    protected static function getResourceBreadcrumbs(string $resource): array
    {
        if (! static::hasResourceBreadcrumbs()) {
            return [];
        }

        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class === null) {
            return [];
        }

        return [[
            'label' => $class::getBreadcrumb(),
            'url' => route('refilament.resource.index', ['resource' => $resource]),
        ]];
    }

    /**
     * The record crumb for this page's breadcrumbs (slice 1.11), inserted
     * between the resource crumb and the page crumb on record pages. Mirrors
     * Filament's `InteractsWithRecord::getBreadcrumbs()`: the record's title,
     * linked to its view page when the current user can view it, else its
     * edit page when they can edit it, else shown plain (never linking to a
     * page the user can't act on). No crumb when there is no record, when
     * the record no longer exists, or when the resource declares no record
     * title.
     *
     * @return array<int, array{label: string, url?: string}>
     */
    protected static function getRecordBreadcrumbs(string $resource, ?Model $record): array
    {
        if ($record === null || ! $record->exists) {
            return [];
        }

        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class === null || ! $class::hasRecordTitle()) {
            return [];
        }

        $title = $class::getRecordTitle($record);

        if ($class::hasPage('view') && $class::canView($record)) {
            return [[
                'label' => $title,
                'url' => route('refilament.resource.view', [
                    'resource' => $resource,
                    'record' => $record->getKey(),
                ]),
            ]];
        }

        if ($class::hasPage('edit') && $class::canEdit($record)) {
            return [[
                'label' => $title,
                'url' => route('refilament.resource.edit', [
                    'resource' => $resource,
                    'record' => $record->getKey(),
                ]),
            ]];
        }

        return [['label' => $title]];
    }

    /**
     * This page's breadcrumbs (slice 1.11), in display order: the resource
     * crumb (list-page link), the record crumb on record pages (linked per
     * authorization), then this page's own crumb as the current (unlinked)
     * entry. Mirrors Filament's `getBreadcrumbs()` shape, serialized as a
     * list of `{ label, url? }` — the omission convention applies to `url`
     * (the current page is never a link). Override for full control; the
     * serializers resolve the resource context the same way getPayload does.
     * (The `$resource` param is optional only to widen the standalone base's
     * no-arg `getBreadcrumbs()` — resource pages always resolve it.)
     *
     * @return array<int, array{label: string, url?: string}>
     */
    public static function getBreadcrumbs(string $resource = '', ?Model $record = null): array
    {
        // A clustered page's chain gains its cluster crumb first (the
        // page-clusters slice), linked to the cluster's redirect URL. The
        // cluster resolves from the URL segment when the page class declares
        // none (built-in pages used directly in a hand-written getPages()
        // map — their resource's `$cluster` still applies).
        $cluster = static::getCluster();

        if ($cluster === null && $resource !== '') {
            $class = app(Refilament::class)->getResourceClass($resource);

            if ($class !== null) {
                $cluster = $class::getCluster();
            }
        }

        return static::unshiftClusterBreadcrumbs([
            ...static::getResourceBreadcrumbs($resource),
            ...static::getRecordBreadcrumbs($resource, $record),
            ['label' => static::getBreadcrumb()],
        ], $cluster);
    }

    /**
     * Serialize the page's breadcrumbs into the page payload. The
     * `breadcrumbs` key is omitted entirely when the panel's global
     * `->breadcrumbs()` toggle is off (slice 1.11 — mirroring Filament's
     * `hasBreadcrumbs()` gate) or the page declares none.
     *
     * @return array{breadcrumbs: array<int, array{label: string, url?: string}>}|array{}
     */
    protected static function serializeBreadcrumbs(string $resource, Refilament $refilament, ?string $record = null): array
    {
        if (! $refilament->panel()->hasBreadcrumbs()) {
            return [];
        }

        // The record model for the record crumb — resolved through the
        // page's own record-binding query (mirroring Filament, where
        // InteractsWithRecord reads the Livewire-bound record). A stale
        // record that no longer resolves simply yields no record crumb.
        $recordModel = null;

        if ($record !== null) {
            $recordModel = static::getRecordRouteBindingEloquentQuery($resource)->find((string) $record);
        }

        $breadcrumbs = static::getBreadcrumbs($resource, $recordModel);

        return $breadcrumbs === [] ? [] : ['breadcrumbs' => $breadcrumbs];
    }

    /**
     * The actions rendered in the page header, right of the title (slice 1.10
     * — docs/ROADMAP.md "1.10 Page header actions"). Mirrors Filament's
     * `getHeaderActions()`, with one deliberate difference: page classes are
     * static (no Livewire instance), so the method receives the request-time
     * resource table id — the same context getPayload() builds from.
     *
     * The built-in ListRecords returns the default CreateAction here; any
     * page (built-in or custom) overrides this to add its own actions.
     *
     * The serializer mutates the returned actions in place (resolving the
     * CreateAction's label, url/modal fallback and authorization) — so this
     * method must return **fresh instances per call** (the `::make()` idiom),
     * never instances cached in a static property (the Filament
     * getCachedHeaderActions() idiom would leak defaults across requests).
     *
     * @return array<int, Action>
     */
    protected static function getHeaderActions(string $resource): array
    {
        return [];
    }

    /**
     * The page's header actions as live instances — the public face of the
     * (protected) getHeaderActions() override point, for the typed
     * page-action endpoint (ResourcePageActionController), which must
     * resolve one action by name and run it against the page's record.
     *
     * @return array<int, Action>
     */
    public static function getHeaderActionInstances(string $resource): array
    {
        return static::getHeaderActions($resource);
    }

    /**
     * Serialize the page's header actions into the page payload. The
     * `pageActions` key is omitted entirely when the page declares none (or
     * every action is filtered out) — the common case ships no extra key.
     *
     * Actions are filtered server-side (slice 4.1 machinery): an action the
     * current user may not run never reaches the client. A CreateAction
     * additionally resolves its defaults here, where the resource context
     * exists:
     *   - the "New {Model}" label from the resource's model-derived title;
     *   - the create authorization gate (a resource the user cannot create
     *     drops the button) unless the action declared its own authorization;
     *   - Filament's getDefaultActionUrl: the create page URL when the
     *     resource registers a create page, else a modal hosting the
     *     resource's form schema.
     *
     * On record pages (a $record is passed) the serializer additionally
     * mirrors Filament's page-vs-modal semantics for the built-ins:
     *   - EditAction / ViewAction (urlPage actions) resolve their per-record
     *     page URL through the resource — the button navigates to the page
     *     when the resource registers it and the user may act on the record,
     *     and is dropped otherwise;
     *   - server actions (DeleteAction …) serialize a runnable endpoint
     *     (`actionUrl`) plus the record key, and DeleteAction carries the
     *     list-page URL it should land on after deleting (the client
     *     navigates instead of reloading — the record is gone).
     *
     * @return array{pageActions: array<int, array<string, mixed>>}|array{}
     */
    protected static function serializeHeaderActions(string $resource, Refilament $refilament, ?Model $record = null): array
    {
        $actions = static::getHeaderActions($resource);

        if ($actions === []) {
            return [];
        }

        $class = $refilament->getResourceClass($resource);

        // The page's slot name in the resource's getPages() map — the
        // endpoint that runs record-scoped page actions resolves the page
        // class through it.
        $pageName = static::pageSlotName($refilament, $resource);

        $serialized = [];

        foreach ($actions as $action) {
            if ($action instanceof CreateAction) {
                if (! $action->hasCustomLabel()) {
                    $action->modelLabel(static::getResourceTitle($resource));
                }

                // The default create gate — a resource the current user
                // cannot create drops the button (mirrors Filament, where
                // CreateAction's default authorization resolves to the
                // resource's create response). Only applied when the action
                // declares no authorization of its own.
                if ($action->getAuthorization() === null && $class !== null && ! $class::canCreate()) {
                    continue;
                }

                // Filament's getDefaultActionUrl: the create page wins when
                // the resource registers one; without it the action falls
                // back to a modal hosting the resource's form. With no
                // resource class at all (unreachable in practice — the
                // route's where() gate only admits discovered ids) the
                // action ships with neither url nor schema, so drop it
                // rather than render a dead button.
                if ($action->getUrl() === null && $action->getSchema() === null) {
                    if ($class === null) {
                        continue;
                    }

                    if ($class::hasPage('create')) {
                        $action->url(route('refilament.resource.create', ['resource' => $resource]));
                    } else {
                        $action->type('create')->schema($class::getFormId());
                    }
                }
            }

            // Record-scoped navigation (EditAction / ViewAction): resolve the
            // per-record page URL the same way the table's row serializer
            // does — the resource's page map + policy gates decide. A URL
            // that resolves nowhere (no page route, or the current user may
            // not act on this record) drops the button.
            if ($record !== null && $action->getUrlPage() !== null && $action->getUrl() === null) {
                $url = $class !== null ? $class::getRecordUrl($action->getUrlPage(), $record) : null;

                if ($url === null) {
                    continue;
                }

                $action->url($url);
            }

            // Record-scoped server actions (DeleteAction …) only make sense
            // where a record exists — a server action with no record to act
            // on would render a dead button, so it is dropped elsewhere.
            $runsOnServer = $record !== null
                && $action->getAction() !== null
                && $action->getUrl() === null
                && $action->getSchema() === null
                && $action->getName() !== null
                && $pageName !== null;

            if ($record !== null) {
                if (! $action->isVisibleFor($record)) {
                    continue;
                }
            } elseif (! $action->isAuthorized()) {
                continue;
            }

            $payload = $action->toArray();

            if ($runsOnServer) {
                $payload['actionUrl'] = route('refilament.resource.action', [
                    'resource' => $resource,
                    'page' => $pageName,
                    'record' => $record->getKey(),
                    'action' => $action->getName(),
                ]);

                // Filament's DeleteAction on record pages redirects to the
                // resource's list page after deleting — the client follows
                // it instead of reloading in place.
                if ($action instanceof DeleteAction) {
                    $payload['redirect'] = $class::getNavigationUrl();
                }
            }

            $serialized[] = $payload;
        }

        return $serialized === [] ? [] : ['pageActions' => $serialized];
    }

    /**
     * The widgets rendered above the page's content slot (slice 1.10 —
     * docs/ROADMAP.md "1.10 Header & footer widgets"), mirroring Filament's
     * `getHeaderWidgets()`. A stats strip above the list table is the
     * canonical example. Widgets are static snapshots — serialized at
     * request time, rendered by the React runtime with no round trips (a
     * widget that opts into the typed data endpoint needs its own resolver
     * registration, like the dashboard's).
     *
     * @return array<int, Widget>
     */
    protected static function getHeaderWidgets(): array
    {
        return [];
    }

    /**
     * The widgets rendered below the page's content slot (slice 1.10),
     * mirroring Filament's `getFooterWidgets()`.
     *
     * @return array<int, Widget>
     */
    protected static function getFooterWidgets(): array
    {
        return [];
    }

    /**
     * The grid column count for the header widgets (slice 1.10) — Filament's
     * default of 2. A widget's own columnSpan overrides its cell in the grid.
     */
    public static function getHeaderWidgetsColumns(): int
    {
        return 2;
    }

    /**
     * The grid column count for the footer widgets (slice 1.10) — a single
     * column, so a footer widget reads as a full-width section.
     */
    public static function getFooterWidgetsColumns(): int
    {
        return 1;
    }

    /**
     * Serialize the page's header/footer widgets into the page payload. Both
     * keys (and their column counts) are omitted when the page declares no
     * widgets — a list page without a stats strip ships no extra keys.
     *
     * @return array<string, mixed>
     */
    protected static function serializePageWidgets(): array
    {
        $payload = [];

        $headerWidgets = static::getHeaderWidgets();

        if ($headerWidgets !== []) {
            $payload['headerWidgets'] = array_map(
                static fn (Widget $widget): array => $widget->toArray(),
                $headerWidgets,
            );
            $payload['headerWidgetsColumns'] = static::getHeaderWidgetsColumns();
        }

        $footerWidgets = static::getFooterWidgets();

        if ($footerWidgets !== []) {
            $payload['footerWidgets'] = array_map(
                static fn (Widget $widget): array => $widget->toArray(),
                $footerWidgets,
            );
            $payload['footerWidgetsColumns'] = static::getFooterWidgetsColumns();
        }

        return $payload;
    }

    /**
     * Extra Inertia props merged into the page payload — a page's own data,
     * computed server-side per request. The pages-as-tables idiom: a page
     * whose payload is mostly its own computed values (reports, dashboards)
     * overrides this; a page that hosts a table overrides getPayload() to
     * merge the table payload instead (the built-in ListRecords is the
     * canonical example).
     *
     * @return array<string, mixed>
     */
    public static function getViewData(string $resource): array
    {
        return [];
    }

    /**
     * The query the {record} route param resolves through — record pages
     * (edit/view) load their model through this so the binding honors the
     * resource's own scoping. Override for soft-delete-aware binding
     * (withTrashed()), mirroring Filament's
     * getRecordRouteBindingEloquentQuery().
     *
     * @return Builder<Model>
     */
    public static function getRecordRouteBindingEloquentQuery(string $resource): Builder
    {
        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class === null) {
            abort(404);
        }

        $model = $class::getModel();

        return $model::query();
    }

    /**
     * Abort with 403 unless the current user may browse this resource's
     * records (slice 4.1 — docs/ROADMAP.md "4.1 Authorization"). Resolves the
     * class from the URL segment and delegates to Resource::authorizeViewAny().
     */
    protected static function authorizeViewAny(string $resource): void
    {
        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class !== null) {
            $class::authorizeViewAny();
        }
    }

    /**
     * Abort with 403 unless the current user may create a record (slice 4.1).
     */
    protected static function authorizeCreate(string $resource): void
    {
        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class !== null) {
            $class::authorizeCreate();
        }
    }

    /**
     * Abort with 403 unless the current user may view the given record
     * (slice 4.1). The record comes from the resource's own scoped query.
     */
    protected static function authorizeView(string $resource, Model $record): void
    {
        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class !== null) {
            $class::authorizeView($record);
        }
    }

    /**
     * Abort with 403 unless the current user may edit the given record
     * (slice 4.1).
     */
    protected static function authorizeEdit(string $resource, Model $record): void
    {
        $class = app(Refilament::class)->getResourceClass($resource);

        if ($class !== null) {
            $class::authorizeEdit($record);
        }
    }

    /**
     * Abort with 403 unless the current user may act on the given record
     * with the given ability (the record-pages slice). The public face of
     * the protected authorizeView()/authorizeEdit() gates — the record-
     * scoped endpoints (record-page form submit) and custom record pages'
     * getPayload() go through here, dispatching 'edit' to the edit gate and
     * anything else to the view gate. Override to tighten a page's own
     * record access.
     */
    public static function authorizeRecord(string $resource, Model $record, string $ability = 'view'): void
    {
        if ($ability === 'edit') {
            static::authorizeEdit($resource, $record);

            return;
        }

        static::authorizeView($resource, $record);
    }

    /**
     * Resolve the {record} route segment to its model and authorize the
     * current user against it (the record-pages slice) — the one-call idiom
     * a record-scoped custom page's getPayload() uses:
     * `static::resolveRecord($resource, (string) $record)` for a read page,
     * `... , 'edit'` for one that edits. Resolved through the page's own
     * record-binding query (soft-delete-aware overrides honored) and gated
     * by the resource's policy via authorizeRecord(). 404s when the record
     * is gone, 403s when the current user may not act on it.
     */
    public static function resolveRecord(string $resource, string $record, string $ability = 'view'): Model
    {
        $model = static::getRecordRouteBindingEloquentQuery($resource)->findOrFail($record);

        static::authorizeRecord($resource, $model, $ability);

        return $model;
    }

    /**
     * The page's slot name in the resource's getPages() map — the key the
     * record-scoped endpoints (page actions, page-form submit) and the page
     * payload serializers use to address this page's URL. Null when the
     * resource class is unknown or the page isn't in the map (a
     * hand-rolled page used outside getPages(), or a stale route).
     */
    protected static function pageSlotName(Refilament $refilament, string $resource): ?string
    {
        $class = $refilament->getResourceClass($resource);

        if ($class === null) {
            return null;
        }

        foreach ($class::getPages() as $name => $registration) {
            if ($registration->getPage() === static::class) {
                return $name;
            }
        }

        return null;
    }

    /**
     * The display name for a resource's records, derived from its model
     * (e.g. "User") — shared by the list, create, edit and view pages.
     *
     * @param  class-string<resource>  $class
     */
    protected static function resourceTitleFor(string $class): string
    {
        return Str::headline(class_basename($class::getModel()));
    }

    protected static function getResourceTitle(string $resource): string
    {
        $class = app(Refilament::class)->getResourceClass($resource);

        return $class === null ? Str::headline($resource) : static::resourceTitleFor($class);
    }
}
